package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_INFO_CACHE".
 */
public class ChatInfoCache {

    private Long id;
    private String senderId;
    private String receiverId;
    private String msg;
    private java.util.Date time;

    public ChatInfoCache() {
    }

    public ChatInfoCache(Long id) {
        this.id = id;
    }

    public ChatInfoCache(Long id, String senderId, String receiverId, String msg, java.util.Date time) {
        this.id = id;
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.msg = msg;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSenderId() {
        return senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

}
