package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMPLAINT_CACHE".
 */
public class ComplaintCache {

    private Long id;
    private String userId;
    private String complainedUserId;
    private Long helpId;
    private String complaints;
    private java.util.Date complaintTime;

    public ComplaintCache() {
    }

    public ComplaintCache(Long id) {
        this.id = id;
    }

    public ComplaintCache(Long id, String userId, String complainedUserId, Long helpId, String complaints, java.util.Date complaintTime) {
        this.id = id;
        this.userId = userId;
        this.complainedUserId = complainedUserId;
        this.helpId = helpId;
        this.complaints = complaints;
        this.complaintTime = complaintTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getComplainedUserId() {
        return complainedUserId;
    }

    public void setComplainedUserId(String complainedUserId) {
        this.complainedUserId = complainedUserId;
    }

    public Long getHelpId() {
        return helpId;
    }

    public void setHelpId(Long helpId) {
        this.helpId = helpId;
    }

    public String getComplaints() {
        return complaints;
    }

    public void setComplaints(String complaints) {
        this.complaints = complaints;
    }

    public java.util.Date getComplaintTime() {
        return complaintTime;
    }

    public void setComplaintTime(java.util.Date complaintTime) {
        this.complaintTime = complaintTime;
    }

}
