package com.example.barry215.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.barry215.greendao.HelpInfoCache;
import com.example.barry215.greendao.PicCache;
import com.example.barry215.greendao.CommentCache;
import com.example.barry215.greendao.UserCache;
import com.example.barry215.greendao.FollowCache;
import com.example.barry215.greendao.HelperCache;
import com.example.barry215.greendao.LoginCache;
import com.example.barry215.greendao.MessageCache;
import com.example.barry215.greendao.ThanksCache;
import com.example.barry215.greendao.ComplaintCache;
import com.example.barry215.greendao.ChatInfoCache;

import com.example.barry215.greendao.HelpInfoCacheDao;
import com.example.barry215.greendao.PicCacheDao;
import com.example.barry215.greendao.CommentCacheDao;
import com.example.barry215.greendao.UserCacheDao;
import com.example.barry215.greendao.FollowCacheDao;
import com.example.barry215.greendao.HelperCacheDao;
import com.example.barry215.greendao.LoginCacheDao;
import com.example.barry215.greendao.MessageCacheDao;
import com.example.barry215.greendao.ThanksCacheDao;
import com.example.barry215.greendao.ComplaintCacheDao;
import com.example.barry215.greendao.ChatInfoCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig helpInfoCacheDaoConfig;
    private final DaoConfig picCacheDaoConfig;
    private final DaoConfig commentCacheDaoConfig;
    private final DaoConfig userCacheDaoConfig;
    private final DaoConfig followCacheDaoConfig;
    private final DaoConfig helperCacheDaoConfig;
    private final DaoConfig loginCacheDaoConfig;
    private final DaoConfig messageCacheDaoConfig;
    private final DaoConfig thanksCacheDaoConfig;
    private final DaoConfig complaintCacheDaoConfig;
    private final DaoConfig chatInfoCacheDaoConfig;

    private final HelpInfoCacheDao helpInfoCacheDao;
    private final PicCacheDao picCacheDao;
    private final CommentCacheDao commentCacheDao;
    private final UserCacheDao userCacheDao;
    private final FollowCacheDao followCacheDao;
    private final HelperCacheDao helperCacheDao;
    private final LoginCacheDao loginCacheDao;
    private final MessageCacheDao messageCacheDao;
    private final ThanksCacheDao thanksCacheDao;
    private final ComplaintCacheDao complaintCacheDao;
    private final ChatInfoCacheDao chatInfoCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        helpInfoCacheDaoConfig = daoConfigMap.get(HelpInfoCacheDao.class).clone();
        helpInfoCacheDaoConfig.initIdentityScope(type);

        picCacheDaoConfig = daoConfigMap.get(PicCacheDao.class).clone();
        picCacheDaoConfig.initIdentityScope(type);

        commentCacheDaoConfig = daoConfigMap.get(CommentCacheDao.class).clone();
        commentCacheDaoConfig.initIdentityScope(type);

        userCacheDaoConfig = daoConfigMap.get(UserCacheDao.class).clone();
        userCacheDaoConfig.initIdentityScope(type);

        followCacheDaoConfig = daoConfigMap.get(FollowCacheDao.class).clone();
        followCacheDaoConfig.initIdentityScope(type);

        helperCacheDaoConfig = daoConfigMap.get(HelperCacheDao.class).clone();
        helperCacheDaoConfig.initIdentityScope(type);

        loginCacheDaoConfig = daoConfigMap.get(LoginCacheDao.class).clone();
        loginCacheDaoConfig.initIdentityScope(type);

        messageCacheDaoConfig = daoConfigMap.get(MessageCacheDao.class).clone();
        messageCacheDaoConfig.initIdentityScope(type);

        thanksCacheDaoConfig = daoConfigMap.get(ThanksCacheDao.class).clone();
        thanksCacheDaoConfig.initIdentityScope(type);

        complaintCacheDaoConfig = daoConfigMap.get(ComplaintCacheDao.class).clone();
        complaintCacheDaoConfig.initIdentityScope(type);

        chatInfoCacheDaoConfig = daoConfigMap.get(ChatInfoCacheDao.class).clone();
        chatInfoCacheDaoConfig.initIdentityScope(type);

        helpInfoCacheDao = new HelpInfoCacheDao(helpInfoCacheDaoConfig, this);
        picCacheDao = new PicCacheDao(picCacheDaoConfig, this);
        commentCacheDao = new CommentCacheDao(commentCacheDaoConfig, this);
        userCacheDao = new UserCacheDao(userCacheDaoConfig, this);
        followCacheDao = new FollowCacheDao(followCacheDaoConfig, this);
        helperCacheDao = new HelperCacheDao(helperCacheDaoConfig, this);
        loginCacheDao = new LoginCacheDao(loginCacheDaoConfig, this);
        messageCacheDao = new MessageCacheDao(messageCacheDaoConfig, this);
        thanksCacheDao = new ThanksCacheDao(thanksCacheDaoConfig, this);
        complaintCacheDao = new ComplaintCacheDao(complaintCacheDaoConfig, this);
        chatInfoCacheDao = new ChatInfoCacheDao(chatInfoCacheDaoConfig, this);

        registerDao(HelpInfoCache.class, helpInfoCacheDao);
        registerDao(PicCache.class, picCacheDao);
        registerDao(CommentCache.class, commentCacheDao);
        registerDao(UserCache.class, userCacheDao);
        registerDao(FollowCache.class, followCacheDao);
        registerDao(HelperCache.class, helperCacheDao);
        registerDao(LoginCache.class, loginCacheDao);
        registerDao(MessageCache.class, messageCacheDao);
        registerDao(ThanksCache.class, thanksCacheDao);
        registerDao(ComplaintCache.class, complaintCacheDao);
        registerDao(ChatInfoCache.class, chatInfoCacheDao);
    }
    
    public void clear() {
        helpInfoCacheDaoConfig.getIdentityScope().clear();
        picCacheDaoConfig.getIdentityScope().clear();
        commentCacheDaoConfig.getIdentityScope().clear();
        userCacheDaoConfig.getIdentityScope().clear();
        followCacheDaoConfig.getIdentityScope().clear();
        helperCacheDaoConfig.getIdentityScope().clear();
        loginCacheDaoConfig.getIdentityScope().clear();
        messageCacheDaoConfig.getIdentityScope().clear();
        thanksCacheDaoConfig.getIdentityScope().clear();
        complaintCacheDaoConfig.getIdentityScope().clear();
        chatInfoCacheDaoConfig.getIdentityScope().clear();
    }

    public HelpInfoCacheDao getHelpInfoCacheDao() {
        return helpInfoCacheDao;
    }

    public PicCacheDao getPicCacheDao() {
        return picCacheDao;
    }

    public CommentCacheDao getCommentCacheDao() {
        return commentCacheDao;
    }

    public UserCacheDao getUserCacheDao() {
        return userCacheDao;
    }

    public FollowCacheDao getFollowCacheDao() {
        return followCacheDao;
    }

    public HelperCacheDao getHelperCacheDao() {
        return helperCacheDao;
    }

    public LoginCacheDao getLoginCacheDao() {
        return loginCacheDao;
    }

    public MessageCacheDao getMessageCacheDao() {
        return messageCacheDao;
    }

    public ThanksCacheDao getThanksCacheDao() {
        return thanksCacheDao;
    }

    public ComplaintCacheDao getComplaintCacheDao() {
        return complaintCacheDao;
    }

    public ChatInfoCacheDao getChatInfoCacheDao() {
        return chatInfoCacheDao;
    }

}
