package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HELPER_CACHE".
 */
public class HelperCache {

    private Long id;
    private Long helpId;
    private String helperId;

    public HelperCache() {
    }

    public HelperCache(Long id) {
        this.id = id;
    }

    public HelperCache(Long id, Long helpId, String helperId) {
        this.id = id;
        this.helpId = helpId;
        this.helperId = helperId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getHelpId() {
        return helpId;
    }

    public void setHelpId(Long helpId) {
        this.helpId = helpId;
    }

    public String getHelperId() {
        return helperId;
    }

    public void setHelperId(String helperId) {
        this.helperId = helperId;
    }

}
