package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HELP_INFO_CACHE".
 */
public class HelpInfoCache {

    private Long id;
    private String userName;
    private String userId;
    private String userSchool;
    private String userSex;
    private java.util.Date publishTime;
    private String userHead;
    private String helpState;
    private String deadTime;
    private String reward;
    private String helpBody;
    private String helpType;
    private String helpTab;
    private String chooseHelperId;
    private String systemHelp;
    private String finisherId;
    private Float rating;

    public HelpInfoCache() {
    }

    public HelpInfoCache(Long id) {
        this.id = id;
    }

    public HelpInfoCache(Long id, String userName, String userId, String userSchool, String userSex, java.util.Date publishTime, String userHead, String helpState, String deadTime, String reward, String helpBody, String helpType, String helpTab, String chooseHelperId, String systemHelp, String finisherId, Float rating) {
        this.id = id;
        this.userName = userName;
        this.userId = userId;
        this.userSchool = userSchool;
        this.userSex = userSex;
        this.publishTime = publishTime;
        this.userHead = userHead;
        this.helpState = helpState;
        this.deadTime = deadTime;
        this.reward = reward;
        this.helpBody = helpBody;
        this.helpType = helpType;
        this.helpTab = helpTab;
        this.chooseHelperId = chooseHelperId;
        this.systemHelp = systemHelp;
        this.finisherId = finisherId;
        this.rating = rating;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserSchool() {
        return userSchool;
    }

    public void setUserSchool(String userSchool) {
        this.userSchool = userSchool;
    }

    public String getUserSex() {
        return userSex;
    }

    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

    public java.util.Date getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(java.util.Date publishTime) {
        this.publishTime = publishTime;
    }

    public String getUserHead() {
        return userHead;
    }

    public void setUserHead(String userHead) {
        this.userHead = userHead;
    }

    public String getHelpState() {
        return helpState;
    }

    public void setHelpState(String helpState) {
        this.helpState = helpState;
    }

    public String getDeadTime() {
        return deadTime;
    }

    public void setDeadTime(String deadTime) {
        this.deadTime = deadTime;
    }

    public String getReward() {
        return reward;
    }

    public void setReward(String reward) {
        this.reward = reward;
    }

    public String getHelpBody() {
        return helpBody;
    }

    public void setHelpBody(String helpBody) {
        this.helpBody = helpBody;
    }

    public String getHelpType() {
        return helpType;
    }

    public void setHelpType(String helpType) {
        this.helpType = helpType;
    }

    public String getHelpTab() {
        return helpTab;
    }

    public void setHelpTab(String helpTab) {
        this.helpTab = helpTab;
    }

    public String getChooseHelperId() {
        return chooseHelperId;
    }

    public void setChooseHelperId(String chooseHelperId) {
        this.chooseHelperId = chooseHelperId;
    }

    public String getSystemHelp() {
        return systemHelp;
    }

    public void setSystemHelp(String systemHelp) {
        this.systemHelp = systemHelp;
    }

    public String getFinisherId() {
        return finisherId;
    }

    public void setFinisherId(String finisherId) {
        this.finisherId = finisherId;
    }

    public Float getRating() {
        return rating;
    }

    public void setRating(Float rating) {
        this.rating = rating;
    }

}
