package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOGIN_CACHE".
 */
public class LoginCache {

    private Long id;
    private Boolean isLogin;
    private java.util.Date lastLoginTime;
    private String userId;
    private String playId;

    public LoginCache() {
    }

    public LoginCache(Long id) {
        this.id = id;
    }

    public LoginCache(Long id, Boolean isLogin, java.util.Date lastLoginTime, String userId, String playId) {
        this.id = id;
        this.isLogin = isLogin;
        this.lastLoginTime = lastLoginTime;
        this.userId = userId;
        this.playId = playId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsLogin() {
        return isLogin;
    }

    public void setIsLogin(Boolean isLogin) {
        this.isLogin = isLogin;
    }

    public java.util.Date getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(java.util.Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getPlayId() {
        return playId;
    }

    public void setPlayId(String playId) {
        this.playId = playId;
    }

}
