package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MESSAGE_CACHE".
 */
public class MessageCache {

    private Long id;
    private String senderId;
    private String receiverId;
    private String messageBody;
    private java.util.Date messageTime;
    private Long helpId;
    private Boolean isRead;

    public MessageCache() {
    }

    public MessageCache(Long id) {
        this.id = id;
    }

    public MessageCache(Long id, String senderId, String receiverId, String messageBody, java.util.Date messageTime, Long helpId, Boolean isRead) {
        this.id = id;
        this.senderId = senderId;
        this.receiverId = receiverId;
        this.messageBody = messageBody;
        this.messageTime = messageTime;
        this.helpId = helpId;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSenderId() {
        return senderId;
    }

    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    public String getReceiverId() {
        return receiverId;
    }

    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    public String getMessageBody() {
        return messageBody;
    }

    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
    }

    public java.util.Date getMessageTime() {
        return messageTime;
    }

    public void setMessageTime(java.util.Date messageTime) {
        this.messageTime = messageTime;
    }

    public Long getHelpId() {
        return helpId;
    }

    public void setHelpId(Long helpId) {
        this.helpId = helpId;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
