package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PIC_CACHE".
 */
public class PicCache {

    private Long id;
    private Long helpId;
    private String picName;

    public PicCache() {
    }

    public PicCache(Long id) {
        this.id = id;
    }

    public PicCache(Long id, Long helpId, String picName) {
        this.id = id;
        this.helpId = helpId;
        this.picName = picName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getHelpId() {
        return helpId;
    }

    public void setHelpId(Long helpId) {
        this.helpId = helpId;
    }

    public String getPicName() {
        return picName;
    }

    public void setPicName(String picName) {
        this.picName = picName;
    }

}
