package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "THANKS_CACHE".
 */
public class ThanksCache {

    private Long id;
    private String userId;
    private String thankerId;

    public ThanksCache() {
    }

    public ThanksCache(Long id) {
        this.id = id;
    }

    public ThanksCache(Long id, String userId, String thankerId) {
        this.id = id;
        this.userId = userId;
        this.thankerId = thankerId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getThankerId() {
        return thankerId;
    }

    public void setThankerId(String thankerId) {
        this.thankerId = thankerId;
    }

}
