package com.example.barry215.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_CACHE".
 */
public class UserCache {

    private String PlayId;
    private String userId;
    private String sex;
    private String userName;
    private String userHead;
    private String userState;
    private String userInfo;
    private String university;
    private String college;
    private String password;
    private String phone;
    private String email;
    private String alipay;

    public UserCache() {
    }

    public UserCache(String userId) {
        this.userId = userId;
    }

    public UserCache(String PlayId, String userId, String sex, String userName, String userHead, String userState, String userInfo, String university, String college, String password, String phone, String email, String alipay) {
        this.PlayId = PlayId;
        this.userId = userId;
        this.sex = sex;
        this.userName = userName;
        this.userHead = userHead;
        this.userState = userState;
        this.userInfo = userInfo;
        this.university = university;
        this.college = college;
        this.password = password;
        this.phone = phone;
        this.email = email;
        this.alipay = alipay;
    }

    public String getPlayId() {
        return PlayId;
    }

    public void setPlayId(String PlayId) {
        this.PlayId = PlayId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserHead() {
        return userHead;
    }

    public void setUserHead(String userHead) {
        this.userHead = userHead;
    }

    public String getUserState() {
        return userState;
    }

    public void setUserState(String userState) {
        this.userState = userState;
    }

    public String getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo;
    }

    public String getUniversity() {
        return university;
    }

    public void setUniversity(String university) {
        this.university = university;
    }

    public String getCollege() {
        return college;
    }

    public void setCollege(String college) {
        this.college = college;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAlipay() {
        return alipay;
    }

    public void setAlipay(String alipay) {
        this.alipay = alipay;
    }

}
